function [A,B] = autoGen_PIPTBStateSpace(in1,in2,uw,mK,IK,rK,mA,IA,lAC,mL,g)
%AUTOGEN_PIPTBSTATESPACE
%    [A,B] = AUTOGEN_PIPTBSTATESPACE(IN1,IN2,UW,MK,IK,RK,MA,IA,LAC,ML,G)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Apr-2021 13:22:42

t2 = lAC.^2;
t3 = rK.^2;
t4 = IA.*IK;
t5 = lAC.*mA.*rK;
t6 = mA.*t3;
t7 = mK.*t3;
t8 = mL.*t3;
t9 = IK.*mA.*t2;
t10 = IA.*t6;
t11 = IA.*t7;
t12 = IA.*t8;
t13 = mK.*t2.*t6;
t14 = mL.*t2.*t6;
t15 = t4+t9+t10+t11+t12+t13+t14;
t16 = 1.0./t15;
A = reshape([0.0,0.0,g.*lAC.*mA.*t16.*(IK+t6+t7+t8),-g.*mA.^2.*rK.*t2.*t16,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0],[4,4]);
if nargout > 1
    B = [0.0;0.0;-t16.*(IK+t5+t6+t7+t8);t16.*(IA+t5+mA.*t2)];
end
