function [ddtheta,ddphi] = autoGen_PIPTBDynamics(in1,in2,uw,mK,IK,rK,mA,IA,lAC,mL,g)
%AUTOGEN_PIPTBDYNAMICS
%    [DDTHETA,DDPHI] = AUTOGEN_PIPTBDYNAMICS(IN1,IN2,UW,MK,IK,RK,MA,IA,LAC,ML,G)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Apr-2021 13:22:41

dtheta = in2(1,:);
theta = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dtheta.^2;
t5 = lAC.^2;
t6 = mA.^2;
t7 = rK.^2;
t8 = IA.*IK;
t9 = t2.^2;
t10 = IK.*mA.*t5;
t11 = IA.*mA.*t7;
t12 = IA.*mK.*t7;
t13 = IA.*mL.*t7;
t14 = lAC.*mA.*rK.*t2.*uw;
t15 = mA.*mK.*t5.*t7;
t16 = mA.*mL.*t5.*t7;
t17 = t5.*t6.*t7;
t18 = t9.*t17;
t19 = -t18;
t20 = t8+t10+t11+t12+t13+t15+t16+t17+t19;
t21 = 1.0./t20;
ddtheta = -t21.*(t14+IK.*uw+(t4.*t17.*sin(theta.*2.0))./2.0+mA.*t7.*uw+mK.*t7.*uw+mL.*t7.*uw-IK.*g.*lAC.*mA.*t3-g.*lAC.*t3.*t6.*t7-g.*lAC.*mA.*mK.*t3.*t7-g.*lAC.*mA.*mL.*t3.*t7);
if nargout > 1
    ddphi = t21.*(t14+IA.*uw+mA.*t5.*uw+lAC.^3.*rK.*t3.*t4.*t6-g.*rK.*t2.*t3.*t5.*t6+IA.*lAC.*mA.*rK.*t3.*t4);
end
